### ISSUE TITLE
Cannot follow link after page flipping on recent Safari

### ISSUE THREAD

**Issue by chrox** [johnfactotum/foliate-js#44]
On Safari (`Version 17.3.1 (19617.2.4.11.12)`) when clicking an anchor link in an EPUB document it will return to the last anchored location instead of following the link. This behavior is not seen on Chrome (`131.0.6778.109`). There is a workaround to mitigate the impact of an issue: after an click on any empty space in the page the links will work again.

This is a screencast on Safari:
![Safari](https://github.com/user-attachments/assets/ad241a05-a4b7-41a7-9785-13199d31fd63)

This is a screencast on Chrome:
![Google Chrome](https://github.com/user-attachments/assets/96b40655-0fee-418f-9ba2-e521cba1d7c8)

How to reproduce?
I use the demo reader in the `foliate-js` repo with this patch to run it on Safari:
```
diff --git a/reader.js b/reader.js
index c4c4c4f..ce6f465 100644
--- a/reader.js
+++ b/reader.js
@@ -3,6 +3,36 @@ import { createTOCView } from './ui/tree.js'
 import { createMenu } from './ui/menu.js'
 import { Overlayer } from './overlayer.js'

+// A groupBy polyfill for foliate-js
+Object.groupBy ??= (iterable, callbackfn) => {
+  const obj = Object.create(null);
+  let i = 0;
+  for (const value of iterable) {
+    const key = callbackfn(value, i++);
+    if (key in obj) {
+      obj[key].push(value);
+    } else {
+      obj[key] = [value];
+    }
+  }
+  return obj;
+};
+
+Map.groupBy ??= (iterable, callbackfn) => {
+  const map = new Map();
+  let i = 0;
+  for (const value of iterable) {
+    const key = callbackfn(value, i++),
+      list = map.get(key);
+    if (list) {
+      list.push(value);
+    } else {
+      map.set(key, [value]);
+    }
+  }
+  return map;
+};
+
```

**Comment by johnfactotum** [comment]
I don't have Safari right now, but this doesn't seem to happen in WebKitGTK.

One idea is that, since it works after clicking on the page, perhaps it's because the iframe isn't focused initially, and so when you click on a link, the iframe is focused before the click event is fired. This focusing might trigger a selectionchange event, and because clicking on a link would not move the caret, it scrolls to the last caret position before pointerup, and the click event never fires.

In any case, it must be related to the series of commits where I tried to make it possible to support caret browsing mode. So 327031aca1c0decf089937310d1622ff5b57c201 should be one of the last good commits, if you want to work around this issue, or try a bisect.

**Comment by chrox** [comment]
Great hint. I’ll check it out and report back.

**Comment by chrox** [comment]
@johnfactotum It seems the follow link is not working on Safari from the very beginning. I checked out the first commit that will open the test document: d5d1541d3bcb118caf0691b7b5404c7ec79a41c0 and at that point it has this kind of problem to follow links after paging flips.

**Comment by johnfactotum** [comment]
I can reproduce the issue with Safari 17.6 on Monterey.

It does appear that my speculations above are essentially correct. And the problem goes away when the part that handles pointer caret change is removed.

So I think I'll just remove that bit for now.
