### ISSUE TITLE
Uncaught TypeError when comparing CFIs with different number of indirections

### ISSUE THREAD

**Issue by chrox** [johnfactotum/foliate-js#45]
How to reproduce:

```
➜  foliate-js git:(d5d1541) ✗ node
Welcome to Node.js v22.9.0.
Type ".help" for more information.
> const CFI = await import("./epubcfi.js");
undefined
> CFI.compare("epubcfi(/6/12)", "epubcfi(/6/12!/4/2/2[preface],/22/1:441");
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at compare (file:///Users/chrox/dev/foliate/src/foliate-js/epubcfi.js:171:37)
    at Module.compare (file:///Users/chrox/dev/foliate/src/foliate-js/epubcfi.js:166:36)
>
```

This patch should fix the issue:
```diff
Enumerating objects: 5, done.
diff --git a/epubcfi.js b/epubcfi.js
index cd16d2b..1829ace 100644
--- a/epubcfi.js
+++ b/epubcfi.js
@@ -167,7 +167,7 @@ export const compare = (a, b) => {
         || compare(collapse(a, true), collapse(b, true))

     for (let i = 0; i < Math.max(a.length, b.length); i++) {
-        const p = a[i], q = b[i]
+        const p = a[i] || [], q = b[i] || []
         const maxIndex = Math.max(p.length, q.length) - 1
         for (let i = 0; i <= maxIndex; i++) {
             const x = p[i], y = q[i]
```

**Comment by johnfactotum** [comment]
Strictly speaking, it probably doesn't make sense to compare `/6/12` and `6/12!/4/2/2[preface],/22/1:441` because the former is technically referencing an element in the package document, not the content document referenced by that element. I suppose it is an abuse of notation that feels rather natural to do, to treat it that way, but I'm not entirely sure whether it is really useful.

**Comment by chrox** [comment]
I described the cfi as valid cfi because it was taken from the `section.cfi` field. And there is a use case to compare a highlight or note with the TOC entries with CFI taken from sections. And the highlight or note can be located in a specific section/TOC entry. See
https://github.com/chrox/readest/blob/main/apps/readest-app/src/utils/toc.ts#L56
and
https://github.com/chrox/readest/blob/main/apps/readest-app/src/utils/toc.ts#L26

**Comment by johnfactotum** [comment]
> I described the cfi as valid cfi because it was taken from the `section.cfi` field.

Yes, it is a valid CFI, but technically, without an indirection (`!`) what it refers to is the `<itemref>` in the package document. Well, at least that's how I interpreted it.

But I suppose there's another case which is not currently supported by foliate-js. When you have a document that is embedded within a section, and when that document is not otherwise included in the spine, to reference fragments within it, you would need to have two or more indirections. And this should be sorted properly. (foliate-js doesn't handle having more than one indirection when generating/resolving CFIs, but that is a separate issue.) From this point of view, it does make sense to sort it this way if the content documents are seen as being embedded in the package document (forming a single "rendition").

> And there is a use case to compare a highlight or note with the TOC entries with CFI taken from sections. And the highlight or note can be located in a specific section/TOC entry.

For getting the TOC entry, the `progress.js` module is specifically designed for that purpose. Currently, in `<foliate-view>`, apart from being used in the `search()` and `addAnnotation()` methods, it's also exposed as the `getProgressOf(index, range)` method. If a range isn't specified it will perform the same kind of match that disregards the fragment identifier in the TOC href, with the index of the section only, without using CFIs.

Note that you should not split on the `#`. In order to support Kindle files, the format of hrefs is considered internal to the book implementation and there's a `splitTOCHref()` method for splitting the href.

**Comment by chrox** [comment]
Great. I will switch to the `splitTOCHref()` method.
