### ISSUE TITLE
Wrong color on dark mode 

### ISSUE THREAD

**Issue by tcanabrava** [johnfactotum/foliate-js#5]
My browser is set to dark mode, and when I try to load `Rust From Zero To Prod` epub I got this:

![image](https://user-images.githubusercontent.com/4027216/219030306-f5006575-59fe-405e-9024-aef6cbdf3a2d.png)

I can't share the book for legal reasons, but if you need a copy I can talk to the author and point here.

**Comment by johnfactotum** [comment]
Currently the demo reader (as well as Foliate's `gtk4` branch) forces `color-scheme: light dark;` on the page. This works with `prefers-color-scheme` to automatically style the page in dark mode. And for the publisher, they can also use the media query in the book's CSS.

But `prefers-color-scheme` is relatively new and probably not widely used in e-books. In the old days, books can either

1. detect dark mode with Apple Books' `__ibooks_internal_theme` attribute,
2. detect dark mode with JavaScript, or
3. most commonly, to just not support dark mode at all; for reading systems, this means that in order to force dark mode, it needs to
   a. provide an invert color filter, or
   b. the option to override colors (like the Dark Reader extension for browsers).

These, except 3b, are supported in Foliate 2.x but not yet implemented in the `gtk4` branch or `foliate-js`.
